---
title: "Relatório dos produtos encontrados"
output: 
    html_document:
        theme: paper
        toc: true
        toc_float: 
            collapsed: false
params:
    database:
        label: "Insira seu banco de dados SQLite gerado pelo Price_indexr"
        value: "C:/Users/vflin/Price_indexr/gpus.sqlite"
        input: file
    months:
        label: "Quantos meses de dados?"
        value: 7
        input: slider
        min: 1
        max: 61
        step: 1
        sep: " "
---

```{r setup, include=FALSE}
library(zoo)
library(DBI)
library(knitr)
library(dplyr)
library(tidyr)
library(scales)
library(plotly)
library(ggplot2)
library(stringr)
library(RSQLite)
library(kableExtra)
library(htmltools)

source("functions.R")

conn <- dbConnect(SQLite(), params$database)
tableNames <- dbListTables(conn)
PRODUCTS <- tableNames %>%
    str_remove("price_indexr-") %>% str_replace_all("_", " ") %>% str_to_upper()

DATES <- allowedDates(params$months)

DATASETS <- list()
for (tab in tableNames) {
    DATASETS[[tab]] <- dbReadTable(conn, tab) %>%
        mutate(Date = as.Date(Date)) %>% .[.$Date %in% DATES,]
}
names(DATASETS) <- PRODUCTS
```

### Melhores ofertas por loja* {.tabset .tabset-pills}

```{r echo=FALSE, results='asis'}
output <- priceByStore(DATASETS)
for (i in seq_along(output)) {
    table <- kableExtra::kable(output[[i]][, c("Name", "Price")], row.names = FALSE) %>%
        kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
    
    catHeader(names(output)[i], level = 4)
    print(table)
}
```

### {.unlisted .unnumbered}

*Melhores ofertas na última verificação no dia `r format(output[[1]]$Date[1], "%d de %B de %Y")`

### Índice de preços

Como vão os preços dos produtos, de maneira geral?

```{r echo=FALSE}
plotIndexr(DATASETS)
```


### Histórico de preços individual {.tabset .tabset-pills}

É assim que o preço deste produto tem se comportado:

```{r echo=FALSE, results='asis'}
for(i in seq_along(DATASETS)){
    fig <- plotPrice(DATASETS[[i]])
    
    catHeader(PRODUCTS[i], level = 4)
    print(htmltools::tagList(fig))
}
```
