---
title: "Relatório dos produtos encontrados"
output: 
    html_document:
        theme: paper
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
params:
    database:
        label: "Insira seu banco de dados SQLite gerado pelo Price_indexr"
        value: "C:/Users/vflins/Price_indexr/gpus.sqlite"
        input: file
    months:
        label: "Quantos meses de dados?"
        value: 7
        input: slider
        min: 1
        max: 61
        step: 1
        sep: " "
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(kableExtra)
library(zoo)
library(DBI)
library(RSQLite)

source("functions.R")

conn <- dbConnect(SQLite(), params$database)
tables <- dbListTables(conn)
products <- tables %>%
    str_remove("price_indexr-") %>% str_replace("_", " ") %>% str_to_upper()

dates <- allowedDates(params$months)

datasets <- list()
for (tab in seq_along(tables)) {
    datasets[[products[tab]]] <- dbReadTable(conn, tables[tab]) %>%
        .[.$Date %in% dates,]
}
names(datasets) <- products
```

# Melhor preço em cada loja

```{r priceByStore}
kable(datasets[[1]])
```

### Isto roda algum código?

```{r}
print("hello world")
```


# Histórico de preços individual

```{r}
df <- mtcars

pl_list <- list()

pl1 <- qplot(cyl, disp, data = df[1:12,])
pl2 <- qplot(mpg, cyl, data = df[13:20,])
pl3 <- qplot(mpg, cyl, data = df[21:30,])
pl4 <- qplot(mpg, cyl, data = df[1:12,])

pl_list[[1]] <- list(pl1, pl3,  "one")
pl_list[[2]] <- list(pl2, pl4,  "two")
```

## header {.tabset}

```{r, results = "asis", echo = FALSE}

for(i in seq_along(pl_list)){
    tmp <- pl_list[[i]]
    # As you want to use tabset level here has to be lower than 
    # parent level (ie, parent is 2, so here you have to use 3)
    catHeader(tmp[[3]], 2)
    lapply(tmp[1:2], print)
}
```
