## Check packages and install missing ones
packages <- c(
    "zoo", "DBI", "shiny", "dplyr", "tidyr", "scales", "plotly", "rmarkdown",
    "ggplot2", "stringr", "RSQLite", "kableExtra", "htmltools")
for (pkg in packages) {
    if (!require(pkg, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)) {
        install.packages(pkg, repos = "https://cloud.r-project.org/")}
    library(pkg, character.only = TRUE)}

message("Using pandoc version:")
rmarkdown::find_pandoc(
    dir = paste0(Sys.getenv("USERPROFILE"),"\\AppData\\Local\\Pandoc"))

args = commandArgs(trailingOnly=TRUE)

if (length(args) <= 2 & length(args) >= 1) {
    params <- list(database = args[[1]])
    if (length(args < 2)) { params$months <- as.integer(7) }
    
    filename <- strsplit(params$database[1], "/")[[1]]
    filename <- filename[length(filename)]

    rmarkdown::render(
        input = "analysis.Rmd", 
        output_format = "html_document",
        output_file = paste0(filename, ".html"),
        params = params)
    
    message(paste0("Output saved in ", getwd()))
} else {
    message("
    Incorrect number of arguments, should be:
    1st.: Provide the path (separated by /) to your SQLite database generated by Pr_ind in a single string.
    2nd.: (Optional, defaults to 7) Integer with number of months to observe, 1 shows only currrent month.
    ")
}

