---
title: "Indicador de Preços das GPUs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: "theme.css"
---

```{r setup, include=FALSE}
cores <- c(
    bg="#222222", fg="#E0E0E0", main="#69B57E", second="#FD5D63", third="#63A2BB")
library(flexdashboard)
prices <- readRDS("data/prices.rds")
```

INÍCIO
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Indicador dos preços

```{r}
prices["semana"] <- as.POSIXct(prices$Date, tz=Sys.timezone()) |> 
    cut.POSIXt(breaks="1 week", labels=F)
temp <- aggregate(prices$Price, list(prices$semana, prices$ProductName), FUN=min)
names(temp) <- c("Semana", "Chip", "Melhor preço")
out <- aggregate(temp$`Melhor preço`, list(temp$Semana), FUN=mean)
plot(out, xlab="Semana", ylab="Índice de preços", type="l")
```

PREÇO E PERFORMACE
=======================================================================

Row {data-height=550}
-----------------------------------------------------------------------

### Melhores preços

```{r}

```

Row {data-height=450}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

